"""
Step 4 + Step 5 generator (week-end deliverables).

This repo intentionally gitignores `outputs/`, so Step 4/5 "filled" docs are generated
from Step 1–3 artifacts when present.

Inputs (generated by existing scripts):
  - outputs/missingness_step1/field_missingness_all.csv
  - outputs/missingness_step3/semantics_by_column.csv (optional but recommended)

Outputs (tracked in Git; safe to share):
  - docs/step4_product_field_review.md
  - docs/step5_external_data_source_evaluation.md
"""

from __future__ import annotations

import argparse
import csv
import subprocess
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path


def _repo_root() -> Path:
    return Path(__file__).resolve().parent.parent.parent


OUTPUTS_STEP1 = Path("outputs/missingness_step1/field_missingness_all.csv")
OUTPUTS_STEP3 = Path("outputs/missingness_step3/semantics_by_column.csv")

DOC_STEP4 = Path("docs/step4_product_field_review.md")
DOC_STEP5 = Path("docs/step5_external_data_source_evaluation.md")


@dataclass(frozen=True)
class Step1Row:
    column_name: str
    taxonomy: str
    taxonomy_key: str
    missing_pct: float
    product_behavior_risk: str
    review_priority: str


@dataclass(frozen=True)
class Step3Row:
    column_name: str
    recommended_verdict: str
    notes_for_step4: str


def _read_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f))


def _safe_float(s: str | None) -> float:
    try:
        return float(s) if s not in (None, "", "—") else 0.0
    except ValueError:
        return 0.0


def _normalize_col(s: str) -> str:
    return (s or "").strip().lower()


def load_step1(step1_csv: Path) -> list[Step1Row]:
    rows = _read_csv(step1_csv)
    out: list[Step1Row] = []
    for r in rows:
        out.append(
            Step1Row(
                column_name=str(r.get("column_name", "")).strip(),
                taxonomy=str(r.get("taxonomy", "")).strip(),
                taxonomy_key=str(r.get("taxonomy_key", "")).strip(),
                missing_pct=_safe_float(r.get("missing_pct")),
                product_behavior_risk=str(r.get("product_behavior_risk", "")).strip(),
                review_priority=str(r.get("review_priority", "")).strip(),
            )
        )
    return out


def load_step3(step3_csv: Path) -> dict[str, Step3Row]:
    rows = _read_csv(step3_csv)
    out: dict[str, Step3Row] = {}
    for r in rows:
        col = str(r.get("column_name", "")).strip()
        if not col:
            continue
        out[_normalize_col(col)] = Step3Row(
            column_name=col,
            recommended_verdict=str(r.get("recommended_verdict", "")).strip(),
            notes_for_step4=str(r.get("notes_for_step4", "")).strip(),
        )
    return out


def _prio_sort_key(prio: str) -> int:
    p = (prio or "").upper()
    if "P0" in p:
        return 0
    if "P1" in p:
        return 1
    if "P2" in p:
        return 2
    return 3


def _md_escape_cell(s: str) -> str:
    return (s or "").replace("|", "\\|").replace("\n", " ").strip()


def build_step4_md(step1: list[Step1Row], step3: dict[str, Step3Row], generated_iso: str) -> str:
    # Put higher priority first; within priority: behavior risk, missing %, then name.
    ordered = sorted(
        step1,
        key=lambda r: (
            _prio_sort_key(r.review_priority),
            0 if r.product_behavior_risk == "High" else 1 if r.product_behavior_risk == "Moderate" else 2,
            -r.missing_pct,
            r.column_name.lower(),
        ),
    )

    top = [r for r in ordered if ("P0" in r.review_priority.upper() or "P1" in r.review_priority.upper())]
    rest = [r for r in ordered if r not in top]

    def row_line(r: Step1Row) -> str:
        s3 = step3.get(_normalize_col(r.column_name))
        flags = ""
        if s3 and s3.recommended_verdict and not s3.recommended_verdict.startswith("OK"):
            flags = f" — {s3.recommended_verdict}"
        suggested = f"{r.review_priority}{flags}"
        notes = s3.notes_for_step4 if s3 and s3.notes_for_step4 else ""
        suggested_cell = _md_escape_cell(suggested)
        behavior = _md_escape_cell(r.product_behavior_risk)
        missing = f"{r.missing_pct:.2f}%"
        meta = _md_escape_cell(f"{r.taxonomy} · missing {missing} · behavior {behavior}")
        if notes:
            meta = _md_escape_cell(f"{meta} · {notes}")
        return (
            f"| `{_md_escape_cell(r.column_name)}` | {suggested_cell} |  |  |  |  | {meta} |"
        )

    table_header = (
        "| Field | Current suggested priority | Agreed priority | OK if unknown for MVP? (Y/N) | "
        "User-facing copy / behavior if unknown | Owner | Notes (from Steps 1–3) |\n"
        "|-------|---------------------------|-----------------|------------------------------|"
        "----------------------------------------|-------|------------------------|"
    )

    top_rows = "\n".join(row_line(r) for r in top) if top else "| _No P0/P1 fields found in Step 1._ |  |  |  |  |  |  |"
    rest_rows = "\n".join(row_line(r) for r in rest)

    return f"""# Step 4 — Product field review (generated)

Generated: **{generated_iso}**

This file is generated from:
- `outputs/missingness_step1/field_missingness_all.csv`
- `outputs/missingness_step3/semantics_by_column.csv` (if present)

## Priority definitions

| Level | Definition |
|-------|------------|
| **P0** | Product cannot function without reliable values |
| **P1** | Major user experience or decision quality |
| **P2** | Explanation, trust, or enrichment |
| **P3** | Optional for this version |

## P0 / P1 candidates (start here)

{table_header}
{top_rows}

## Remaining fields (P2 / P3 / informational)

{table_header}
{rest_rows}

## Decision log

| Date | Decision | Rationale |
|------|----------|-----------|
| | | |
"""


def build_step5_md(step1: list[Step1Row], generated_iso: str) -> str:
    # Step 5 is scoped to candidates that can help P0/P1 fields or obvious backfills.
    p0p1 = [r for r in step1 if ("P0" in r.review_priority.upper() or "P1" in r.review_priority.upper())]
    p0p1_sorted = sorted(p0p1, key=lambda r: (_prio_sort_key(r.review_priority), -r.missing_pct, r.column_name.lower()))

    mapping_header = "| Field (P0/P1) | Candidate source | Join key (parcel ID / address / geometry) |\n|---|---|---|"
    mapping_rows = "\n".join(
        f"| `{_md_escape_cell(r.column_name)}` |  |  |" for r in p0p1_sorted
    ) or "| _(No P0/P1 fields detected yet — run Step 1 or review priority rules.)_ |  |  |"

    return f"""# Step 5 — External data source / API evaluation (generated)

Generated: **{generated_iso}**

This file seeds Step 5 using Step 1 review priority. Update it after the Step 4 workshop confirms the **agreed** P0/P1 list.

## Field ↔ source mapping

{mapping_header}
{mapping_rows}

## Evaluation matrix (use per candidate source)

| Criterion | Notes / score (1–5 or pass/fail) |
|-----------|-----------------------------------|
| **Coverage** (geography & parcel universe) | |
| **Freshness** (update cadence vs product need) | |
| **Cost** (per-call, seat, or bulk license) | |
| **Rate limits** (and batching strategy) | |
| **Join stability** (APN format, city normalization) | |
| **Spatial match quality** (footprint vs parcel polygon) | |
| **Manual QA burden** (spot checks, edge cases) | |
| **Licensing & redistribution** (cache in DB? expose to users?) | |
| **Operational risk** (downtime, key rotation, compliance) | |

## Pilot plan

1. **Sample size:** e.g. 2,000 parcels stratified by `scity` and missingness pattern.
2. **Success metrics:** fill rate uplift, disagreement rate vs current values, latency.
3. **Rollback:** how to revert or flag enriched rows if quality fails.

## Outcome

| Source | Integrate? (Y/N/Maybe) | Conditions | Owner | Target date |
|--------|------------------------|------------|-------|-------------|
| | | | | |
"""


def _write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _run(cmd: list[str]) -> int:
    p = subprocess.run(cmd, cwd=_repo_root(), stdout=sys.stdout, stderr=sys.stderr)
    return int(p.returncode)


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Generate Step 4 + Step 5 docs from audit outputs")
    p.add_argument("--step1-csv", type=Path, default=_repo_root() / OUTPUTS_STEP1)
    p.add_argument("--step3-csv", type=Path, default=_repo_root() / OUTPUTS_STEP3)
    p.add_argument("--out-step4", type=Path, default=_repo_root() / DOC_STEP4)
    p.add_argument("--out-step5", type=Path, default=_repo_root() / DOC_STEP5)
    p.add_argument(
        "--run-step1",
        action="store_true",
        help="Run Step 1 script before generating docs",
    )
    p.add_argument(
        "--run-step3",
        action="store_true",
        help="Run Step 3 script before generating docs (implies Step 1 since Step 3 imports it)",
    )
    return p.parse_args()


def main() -> None:
    args = parse_args()

    if args.run_step3:
        args.run_step1 = True

    if args.run_step1:
        rc = _run([sys.executable, "tools/audits/field_missingness_classification.py"])
        if rc != 0:
            raise SystemExit(rc)

    if args.run_step3:
        rc = _run([sys.executable, "tools/audits/field_semantics_audit_step3.py"])
        if rc != 0:
            raise SystemExit(rc)

    generated = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    if not args.step1_csv.exists():
        stub4 = f"""# Step 4 — Product field review (stub)

Generated: **{generated}**

Missing input: `{OUTPUTS_STEP1.as_posix()}`.

Run Step 1 first:

```bash
python tools/audits/field_missingness_classification.py
```
"""
        stub5 = f"""# Step 5 — External data source / API evaluation (stub)

Generated: **{generated}**

Missing input: `{OUTPUTS_STEP1.as_posix()}`.

Run Step 1 first:

```bash
python tools/audits/field_missingness_classification.py
```
"""
        _write_text(args.out_step4, stub4)
        _write_text(args.out_step5, stub5)
        print(f"Wrote {args.out_step4}")
        print(f"Wrote {args.out_step5}")
        return

    step1 = load_step1(args.step1_csv)
    step3 = load_step3(args.step3_csv) if args.step3_csv.exists() else {}

    _write_text(args.out_step4, build_step4_md(step1, step3, generated))
    _write_text(args.out_step5, build_step5_md(step1, generated))
    print(f"Wrote {args.out_step4}")
    print(f"Wrote {args.out_step5}")


if __name__ == "__main__":
    main()

